### ISSUE TITLE
new entry

### ISSUE THREAD

**Issue by danyball** [stencil-community/awesome-stencil#1]
Hi @christian-bromann 

Could you add our Design System to your list?

- [Swisscom SDX](https://sdx.swisscom.com/) - the design system of the leading telecom provider in switzerland, called "Swisscom Design eXperience"

**Comment by christian-bromann** [comment]
Hey 👋 

That's awesome!

would you be interest to make a pull request or should I go ahead and just add it?

**Comment by danyball** [comment]
Please just add it, thanks! :)

**Comment by danyball** [comment]
Thanks, my fault, SDX is called "Swisscom Digitial eXperience". Could you correct that?

**Comment by christian-bromann** [comment]
Corrected!
